apiVersion: v1
kind: Service
metadata:
  name: catalog
  labels: 
    app: catalog
spec:
  type: NodePort
  selector:
    app: catalog
  ports:
    - nodePort: 30666
      port: 80
      protocol: TCP
      targetPort: 80